services:
  db:
    image: mysql:8.0
    container_name: routine_mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: routine_app
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-ppassword"]
      interval: 3s
      timeout: 3s
      retries: 40
      start_period: 5s

volumes:
  mysql_data:

