services:
  db:
    image: postgres:16
    container_name: routine_postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: routine_app
      POSTGRES_USER: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 40
      start_period: 5s

volumes:
  pg_data:
